export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#416373",
        "primary-container": "#7496a8",
        "primary-fixed": "#c4e8fb",
        "primary-fixed-dim": "#a9ccdf",
        "secondary": "#02658d",
        "secondary-container": "#8bd1ff",
        "secondary-fixed": "#c6e7ff",
        "secondary-fixed-dim": "#88cffc",
        "sky-accent": "#6EB5E1",
        "slate-muted": "#7496A8",
        "onyx-text": "#232324",
        "soft-shell": "#F9F9F9",
        "pure-white": "#FFFFFF",
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#42484b",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#72787c",
        "outline-variant": "#c1c7cc",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "section-padding-sm": "64px",
        "section-padding-lg": "120px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-gap": "16px",
        "gutter": "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "button-text": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "button-text": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
